apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-track-cert-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    # Run this hook after sync completes
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    # Don't fail the sync if this hook fails (negative weight = optional)
    argocd.argoproj.io/hook-weight: "-5"
    # This hook is created by ArgoCD sync, don't track it
    argocd.argoproj.io/sync-wave: "-1"
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    metadata:
      name: argocd-track-cert-secrets
    spec:
      restartPolicy: Never
      serviceAccountName: argocd-cert-secret-tracker
      containers:
      - name: kubectl
        image: alpine/k8s:1.29.3
        command:
        - /bin/sh
        - -c
        - |
          set -e
          NAMESPACE="{{ .Release.Namespace }}"
          
          # Try to get application name from Application resource in argocd namespace
          # This matches the ApplicationSet pattern: mail-in-a-pods-{cluster-name}
          APP_NAME=$(kubectl get application -n argocd -o json 2>/dev/null | \
            jq -r ".items[] | select(.spec.destination.namespace == \"$NAMESPACE\" and (.metadata.name | startswith(\"mail-in-a-pods-\"))) | .metadata.name" | head -1 || echo "")
          
          # Fallback: try to infer from Certificate tracking-id or use default pattern
          if [ -z "$APP_NAME" ]; then
            # Check if we have a Certificate with tracking-id to infer app name
            CERT_TRACKING=$(kubectl get certificate -n "$NAMESPACE" -o jsonpath='{.items[0].metadata.annotations.argocd\.argoproj\.io/tracking-id}' 2>/dev/null | cut -d: -f1 || echo "")
            if [ -n "$CERT_TRACKING" ]; then
              APP_NAME="$CERT_TRACKING"
            else
              # Try to get cluster name from destination.name in Application spec
              CLUSTER_NAME=$(kubectl get application -n argocd -o json 2>/dev/null | \
                jq -r ".items[] | select(.spec.destination.namespace == \"$NAMESPACE\" and (.metadata.name | startswith(\"mail-in-a-pods-\"))) | .spec.destination.name" | head -1 || echo "")
              if [ -z "$CLUSTER_NAME" ]; then
                CLUSTER_NAME="argocd-local"
              fi
              APP_NAME="mail-in-a-pods-${CLUSTER_NAME}"
            fi
          fi
          
          echo "Adding ArgoCD tracking annotations to cert-manager Secrets..."
          echo "App Name: $APP_NAME"
          echo "Namespace: $NAMESPACE"
          
          # Get all Secrets with cert-manager.io/certificate-name annotation
          SECRETS=$(kubectl get secrets -n "$NAMESPACE" -o json 2>/dev/null | \
            jq -r '.items[] | select(.metadata.annotations."cert-manager.io/certificate-name") | .metadata.name' || echo "")
          
          if [ -z "$SECRETS" ]; then
            echo "No cert-manager Secrets found in namespace $NAMESPACE"
            exit 0
          fi
          
          echo "Found cert-manager Secrets: $SECRETS"
          
          # Add tracking annotation and sync-wave to each Secret
          # sync-wave: "1" ensures Secret appears after Gateway (wave 0) in dependency graph
          for SECRET in $SECRETS; do
            TRACKING_ID="$APP_NAME:v1/Secret:$NAMESPACE/$SECRET"
            CURRENT_ANNOTATION=$(kubectl get secret "$SECRET" -n "$NAMESPACE" -o jsonpath='{.metadata.annotations.argocd\.argoproj\.io/tracking-id}' 2>/dev/null || echo "")
            CURRENT_WAVE=$(kubectl get secret "$SECRET" -n "$NAMESPACE" -o jsonpath='{.metadata.annotations.argocd\.argoproj\.io/sync-wave}' 2>/dev/null || echo "")
            
            ANNOTATIONS_TO_ADD=""
            
            if [ "$CURRENT_ANNOTATION" != "$TRACKING_ID" ]; then
              ANNOTATIONS_TO_ADD="argocd.argoproj.io/tracking-id=$TRACKING_ID"
              echo "Adding tracking annotation to Secret $SECRET: $TRACKING_ID"
            else
              echo "Secret $SECRET already has correct tracking annotation: $TRACKING_ID"
            fi
            
            if [ "$CURRENT_WAVE" != "1" ]; then
              if [ -n "$ANNOTATIONS_TO_ADD" ]; then
                ANNOTATIONS_TO_ADD="$ANNOTATIONS_TO_ADD argocd.argoproj.io/sync-wave=1"
              else
                ANNOTATIONS_TO_ADD="argocd.argoproj.io/sync-wave=1"
              fi
              echo "Setting sync-wave=1 for Secret $SECRET (to appear after Gateway)"
            else
              echo "Secret $SECRET already has sync-wave=1"
            fi
            
            if [ -n "$ANNOTATIONS_TO_ADD" ]; then
              kubectl annotate secret "$SECRET" -n "$NAMESPACE" \
                $ANNOTATIONS_TO_ADD \
                --overwrite 2>&1 || echo "Warning: Failed to annotate $SECRET, continuing..."
            fi
          done
          
          echo "Completed tracking annotation updates"
